#! /bin/bash -ex

USERID=$(id -u)
GROUPID=$(id -g)

sed -i -e "s#USERID=.*#USERID=${USERID}#" .env
sed -i -e "s#GROUPID=.*#GROUPID=${GROUPID}#" .env
docker build -f os.Dockerfile --build-arg UID="$USERID" --build-arg GID="$GROUPID"  -t kernel .
docker build -f nginx.Dockerfile -t nginx-app .
docker build -f php.Dockerfile -t php-app .
docker build -f php82.Dockerfile -t php82-app .
docker build -f php84.Dockerfile -t php84-app .
docker build -f dns.Dockerfile -t dns-app .
docker build -f db.Dockerfile -t db-app .