#! /bin/bash

UID=$(id -u)
GID=$(id -g)

docker build -f os.Dockerfile --build-arg UID="$UID" --build-arg GID="$GID"  -t kernel .
docker build -f nginx.Dockerfile -t nginx-app .
docker build -f php.Dockerfile -t php-app .
docker build -f dns.Dockerfile -t dns-app .