version: '3'
services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: '123456'
    networks:
      development:
        ipv4_address: 100.100.10.3
    volumes:
      - 'database:/var/lib/mysql'
  nginx:
    image: nginx-app
    restart: always
    networks:
      development:
        ipv4_address: 100.100.10.2
    volumes:
      - 'nginx:/etc/nginx/vhosts'
      - 'php-fpm:/var/opt/remi/php81/run/php-fpm'
      - 'wsl-src:/home/projects'
  php:
    image: php-app
    restart: always
    networks:
      development:
        ipv4_address: 100.100.10.4
    volumes:
      - 'php-fpm:/var/opt/remi/php81/run/php-fpm'
      - 'wsl-src:/home/projects'
  mutagen:
    image: mutagen
    restart: always
    volumes:
      - '/c/xampp/htdocs:/home/alpha'
      - 'wsl-src:/home/beta'

networks:
  development:
    ipam:
      config:
        - subnet: '100.100.10.0/24'

volumes:
  nginx:
  database:
  php-fpm:
  wsl-src: