version: '3'
services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: '123456'
    networks:
      development:
        ipv4_address: 100.100.10.3
    volumes:
      - 'database:/var/lib/mysql'
  nginx:
    image: nginx
    restart: always
    networks:
      development:
        ipv4_address: 100.100.10.2
    volumes:
      - 'nginx:/etc/nginx/vhosts'
      - 'php-fpm:/var/opt/remi/php81/run/php-fpm'
      - '/opt/public_html:/home/projects'
  php:
    image: php
    restart: always
    networks:
      development:
        ipv4_address: 100.100.10.4
    volumes:
      - 'php-fpm:/var/opt/remi/php81/run/php-fpm'
      - '/opt/public_html:/home/projects'
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      UPLOAD_LIMIT: 2G
    networks:
      development:
        ipv4_address: 100.100.10.5

networks:
  development:
    ipam:
      config:
        - subnet: '100.100.10.0/24'

volumes:
  nginx:
  database:
  php-fpm: