version: '3'
# noinspection ComposeUnknownKeys
name: lemp
services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: '123456'
    networks:
      development:
        ipv4_address: 100.100.10.3
    volumes:
      - 'database:/var/lib/mysql'
  nginx:
    image: nginx-app
    restart: always
    networks:
      development:
        ipv4_address: 100.100.10.2
    env_file: [.env]
    volumes:
      - 'nginx:/etc/nginx/vhosts'
      - "${CAROOT}:/etc/nginx/ssl"
      - 'php-fpm:/var/opt/remi/php81/run/php-fpm'
      - "${PROJECTS_ROOT}:/home/projects"
  php:
    image: php-app
    restart: always
    networks:
      development:
        ipv4_address: 100.100.10.4
    volumes:
      - 'php-fpm:/var/opt/remi/php81/run/php-fpm'
      - "${PROJECTS_ROOT}:/home/projects"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      UPLOAD_LIMIT: 2G
    networks:
      development:
        ipv4_address: 100.100.10.5
  dns:
    image: dns-app
    restart: always
    env_file: [.env]
    networks:
      development:
        ipv4_address: 100.100.10.6
    volumes:
      - "${CAROOT}:/root/.local/share/mkcert"
      - 'php-fpm:/var/opt/remi/php81/run/php-fpm'
      - '/etc/hosts:/etc/host.hosts'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - "${PROJECTS_ROOT}/lemp:/home/projects/lemp"

networks:
  development:
    ipam:
      config:
        - subnet: '100.100.10.0/24'

volumes:
  nginx:
  database:
  php-fpm: