#! /bin/bash

./build
docker compose up -d
docker cp lemp-dns-1:/usr/bin/mkcert ./mkcert
chmod +x ./mkcert
CAROOT=$(./mkcert -CAROOT)
sed -i -e "s#CAROOT=.*#CAROOT=${CAROOT}#" .env
./mkcert -install
rm -f mkcert
# To pick up new CAROOT env variable change if it occurs.
docker compose up -d