#! /bin/bash -ex

./build
docker compose up -d
docker cp lemp-dns-1:/usr/bin/mkcert ./mkcert
chmod +x ./mkcert
CAROOT=$(./mkcert -CAROOT)
sed -i -e "s#MKCERT_ROOT=.*#MKCERT_ROOT=${CAROOT}#" .env
./mkcert -install
rm -f mkcert
docker exec lemp-dns-1 composer create-project --repository '{"type":"vcs", "url":"https://github.com/grey-dev-0/lemp-server"}' --keep-vcs --stability dev grey-dev-0/lemp-server /home/projects/lemp
# To pick up new CAROOT env variable change if it occurs.
docker compose restart
docker exec -w /home/projects/lemp lemp-dns-1 php artisan lemp:setup
docker exec -itw /home/projects/lemp lemp-dns-1 npm i
docker exec -itw /home/projects/lemp lemp-dns-1 npm run build
docker exec lemp-dns-1 chown -R user:user /home/projects/lemp
docker exec -w /home/projects/lemp lemp-dns-1 chmod 777 -R storage bootstrap/cache
